simple_scan_viz:
  ros__parameters:
    scan_topic: "/scan"
    marker_frame_id: "map"
    tf_timeout: 0.3

    # FOV/ROI
    fov_deg: 120.0
    fov_center_deg: 0.0
    roi_min_dist: 0.2
    roi_max_dist: 6.0

    # 클러스터링/표시
    db_min_samples: 5
    center_scale: 0.12

    # 링(경계) CSV
    outer_bound_csv: ""
    inner_bound_csv: ""

    # 분류 기준
    window_sec: 1.0
    lidar_hz: 40.0
    Ts: 0.1
    Td: 0.5
    static_radius: 1.0
    dynamic_radius: 2.0
