/**:
  ros__parameters:
    ## Parameter for MPC solver
    dT: 0.1 # time step duration (unit: s)
    mpc_steps_N: 20 # number of steps in the Prediction horizon (N*dT = prediction horizon)
    vehicle_L: 0.33020 # wheelbase (unit: m) (lf + lr = 0.15875 + 0.17145)

    max_speed: 8.0 # Maximum speed (unit: m/s)
    mpc_ref_vel: 6.0 # Reference velocity (unit: m/s)
    mpc_ref_cte: 0.0 # Reference cross-track error (centered on path)
    mpc_ref_epsi: 0.0 # Reference psi error (aligned with path)

    mpc_w_cte: 1.0 # Contouring error weight
    mpc_w_s: 1.0 # Progress weight
    mpc_w_lag: 1.0 # Lag error weight
    mpc_w_vel: 1.0 # Velocity weight
    mpc_w_p: 1.0 # Progress speed weight (p=ds/dt)
    mpc_w_delta: 1.0 # Steering weight
    mpc_w_accel: 1.0 # Acceleration weight
    mpc_w_delta_d: 1.0 # Steering change weight
    mpc_w_delta_p: 1.0 # Progress speed change weight (d p = d (ds/dt))

    mpc_max_steering: 0.36 # Maximum steering angle (unit: rad)
    mpc_max_throttle: 5.0 # Maximum throttle (unit: m/s^2)
    mpc_bound_value: 1000.0

    p_min: 0.0 # Lower bound for progress state
    p_max: 6.5 # Upper bound for progress state

    x_min: -200.0 # Lower bound for x state
    x_max: 200.0 # Upper bound for x state

    y_min: -200.0 # Lower bound for y state
    y_max: 200.0 # Upper bound for y state

    psi_min: -1000.0 # Lower bound for psi state
    psi_max: 1000.0 # Upper bound for psi state

    s_min: 0.0 # Lower bound for s state
    s_max: 200.0 # Upper bound for s state

    d_v_bound: 1.5 # Bound for velocity change (unit: m/s^2)
    d_theta_bound: 0.2 # Bound for steering angle change (unit: rad/s)
    d_p_bound: 1.5 # Bound for progress speed change (unit: m/s^2)

    # Parameters for control loop
    debug_mode: true
    delay_mode: true
    throttle_mode: false
    car_width: 0.31 # F1TENTH Gym actual width
    spline_poly_order: 3
    goal_threshold: 2.0 # unit: m
    controller_freq: 15.0
    path_folder_name: nochun_for_mpcc  # Map-specific folder name (relative path used in code)
    inflation_factor: 0.8
    lag_time: 0.05
    arc_length_min_dist_tol: 0.05
    integration_mode: 'Euler'
    ipopt_verbose: true
    linear_solver: 'mumps'  # Options: 'ma57' (HSL, faster, requires license), 'mumps' (free, default)

    # Frame names
    car_frame: ego_racecar/base_link

    # Topic names for F1TENTH Gym
    odom_topic_name: /ego_racecar/odom
    goal_topic_name: /goal_pose
    cmd_vel_topic_name: /drive
    localized_pose_topic_name: /ego_racecar/odom
