slam_toolbox:
  ros__parameters:
    # Frame IDs - F1TENTH에 맞게 설정
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    scan_topic: /scan

    # Basic settings
    use_sim_time: false
    mode: mapping

    # SLAM parameters
    resolution: 0.05
    map_update_interval: 0.5  # 더 자주 업데이트
    minimum_travel_distance: 0.2  # 더 민감하게
    minimum_travel_heading: 0.2   # 더 민감하게

    # === 자유공간 생성 핵심 설정 ===
    # 라이다 범위 설정 (자유공간 생성에 중요)
    max_laser_range: 12.0  # 증가
    minimum_laser_range: 0.05  # 감소
    
    # 자유공간 마킹 강화
    mark_threshold: 0.0
    update_factor_free: 0.6     # 증가 - 자유공간을 더 적극적으로 마킹
    update_factor_occupied: 0.7  # 감소 - 장애물 마킹을 덜 적극적으로
    
    # 맵 임계값 조정
    occupied_threshold: 0.70    # 증가 - 장애물로 판단하는 기준 상향
    free_threshold: 0.20        # 감소 - 자유공간으로 판단하는 기준 하향
    
    # 스캔 품질 향상
    use_scan_barycenter: true
    use_scan_matching: true
    
    # 최소 빔 개수 감소 (더 많은 스캔 포인트 활용)
    minimum_beam_count: 3
    
    # 스캔 버퍼 설정
    scan_buffer_size: 20 
    scan_buffer_maximum_scan_distance: 12.0

    # === 루프 클로저 설정 ===
    do_loop_closing: true
    loop_search_maximum_distance: 5.0  # F1TENTH 트랙 크기에 맞게 조정 맵이 작으면 5로 설정
    loop_search_space_dimension: 5.0  # 이것도 맵이 작으면 5로 설정
    
    # 루프 매칭 파라미터
    loop_match_minimum_chain_size: 5    # 감소 - 더 빠른 루프 감지
    loop_match_minimum_response_coarse: 0.25  # 감소 - 더 관대한 매칭
    loop_match_minimum_response_fine: 0.3     # 감소
    loop_match_maximum_variance_coarse: 4.0   # 증가 - 더 유연한 매칭
    
    # 최적화 빈도
    optimize_every_n_nodes: 8  # 더 자주 최적화

    # === 스캔 매칭 향상 ===
    correlation_search_space_dimension: 0.6   # 감소 - 더 빠른 처리
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.08  # 감소
    
    # 링크 매칭
    link_match_minimum_response_fine: 0.08  # 감소 - 더 관대한 매칭
    link_scan_maximum_distance: 1.5         # 감소
    
    # 각도/거리 페널티
    minimum_angle_penalty: 0.8   # 감소
    minimum_distance_penalty: 0.3  # 감소
    use_response_expansion: true

    # === 성능 최적화 ===
    # 변환 타임아웃
    transform_timeout: 0.15  # 감소 - 더 빠른 반응
    
    # 매칭 품질
    coarse_search_angle_offset: 0.349
    fine_search_angle_offset: 0.00349
    
    # 디버깅
    debug_logging: false
    enable_interactive_mode: true

    # 차량 크기 설정
    footprint: "[[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]"
    robot_radius: 0.3